language: ruby
rvm:
  - "1.9.3"
  - "2.2.0"
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
before_install:
  - sudo apt-get install libnss3
  - gem install hoe rake-compiler minitest
script: rake compile test gem
