install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - ruby --version
  - gem --version
  - bundle install

  - ps: |
        if ($env:isx64 -eq "1")
        {
          $(new-object net.webclient).DownloadFile('http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/40.0b4/win64/en-US/Firefox%20Setup%2040.0b4.exe', 'C:\firefox-setup.exe')
          cmd /c C:\firefox-setup.exe -ms
          $env:SOFTOKN_PATH = 'C:\Program Files\Mozilla Firefox\softokn3.dll'
          $env:PATH = 'C:\Program Files\Mozilla Firefox;' + $env:PATH
        }

build: off

test_script:
  - bundle exec rake compile test gem

environment:
  matrix:
    - ruby_version: "193"
    #- ruby_version: "200"
    #- ruby_version: "200-x64"
    #- ruby_version: "21"
    #- ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
      isx64: "1"
